name: Check

on: push

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install cpplint
      - run: dotnet tool restore
      - run: dotnet paket restore
      - run: dotnet fsi lint.fsx
        working-directory: sound
